[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

[profile.release-lto]
inherits = "release"
lto = "thin"

[dependencies]
clap = "3.0.0-beta.5"
advent_of_code_traits = "0.1.0"
itertools = "0.10"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
regex = "1.5"
ahash = "0.7"
string-interner = "0.14"