[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[profile.release-lto]
inherits = "release"
lto = "thin"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
advent_of_code_traits = "0.1.0"
itertools = "0.10"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
regex = "1.7"
ahash = "0.8"
string-interner = "0.14"
nalgebra = "0.29"
