on:
  push

name: Lint

jobs:
  check:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache rust artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}-v5

      - name: Run cargo fmt
        run: |
          cargo fmt --all -- --check

      - name: Run clippy
        run: |
          cargo clippy -- -D warnings