on:
  push

name: Run

jobs:
  run:
    name: Run aoc days
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install stable rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Cache rust artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo build
        run: |
          cargo build --release

      - name: Run days
        run: |
          ./target/release/aoc2021 --day 1