on:
  push

name: Run

jobs:
  run:
    name: Run aoc days
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache rust artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}-v5

      - name: Run cargo build
        run: |
          cargo build --profile release-lto
        env:
          RUSTFLAGS: '-C target-cpu=native'

      - name: Run 2022 days
        run: |
          # preload cache
          ./target/release-lto/aoc --year 2022 &>/dev/null
          time ./target/release-lto/aoc --year 2022

      - name: Run 2021 days
        run: |
          time ./target/release-lto/aoc --year 2021

      - name: Run 2019 days
        run: |
          time ./target/release-lto/aoc --year 2019
