on: push

name: Run

jobs:
  run:
    name: Run aoc days
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Cache rust artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}-{{ hashFiles('rust-toolchain.toml') }}-v5

      - name: Cache inputs
        uses: actions/cache@v3
        with:
          path: |
            inputs
          key: aoc-inputs-${{ hashFiles('inputs/**') }}

      - name: Run cargo build
        run: |
          cargo build --release
        env:
          RUSTFLAGS: "-C target-cpu=native"

      - name: Fetch inputs
        env:
          AOC_SESSION: ${{ secrets.AOC_SESSION }}
        run: |
          pip3 install -r scripts/requirements.txt
          python3 ./scripts/fetch_inputs.py

      - name: Run 2023 days
        run: |
          time ./target/release/aoc --year 2023

      - name: Run 2022 days
        run: |
          time ./target/release/aoc --year 2022

      - name: Run 2021 days
        run: |
          time ./target/release/aoc --year 2021

      - name: Run 2019 days
        run: |
          time ./target/release/aoc --year 2019
