on:
  push

name: Run

jobs:
  run:
    name: Run aoc days
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install stable rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Cache rust artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}-v3

      - name: Run cargo build
        run: |
          cargo build --profile release-lto

      - name: Run 2021 days
        run: |
          ./target/release-lto/aoc2021 --day 1
          ./target/release-lto/aoc2021 --day 2
          ./target/release-lto/aoc2021 --day 3
          ./target/release-lto/aoc2021 --day 4
          ./target/release-lto/aoc2021 --day 5
          ./target/release-lto/aoc2021 --day 6
          ./target/release-lto/aoc2021 --day 7
          ./target/release-lto/aoc2021 --day 8
          ./target/release-lto/aoc2021 --day 9
          ./target/release-lto/aoc2021 --day 10
          ./target/release-lto/aoc2021 --day 11
          ./target/release-lto/aoc2021 --day 12
          ./target/release-lto/aoc2021 --day 13
          ./target/release-lto/aoc2021 --day 14
          ./target/release-lto/aoc2021 --day 15

      - name: Run 2019 days
        run: |
          ./target/release-lto/aoc2021 --year 2019 --day 1
          ./target/release-lto/aoc2021 --year 2019 --day 2
          ./target/release-lto/aoc2021 --year 2019 --day 3
          ./target/release-lto/aoc2021 --year 2019 --day 4
          ./target/release-lto/aoc2021 --year 2019 --day 5
